#!/bin/bash

# Script de diagnóstico para Cloud Functions

echo "🔍 Diagnóstico de Cloud Functions"
echo "=================================="
echo ""

PROJECT="agenda-solar"

echo "1️⃣ Verificando tokens FCM en Firestore..."
echo ""
echo "Ejecuta este comando en Firebase Console o usa la SDK:"
echo ""
echo "Firestore → users → (selecciona un usuario) → Busca campo 'fcmToken'"
echo ""
echo "Si no existe o está vacío:"
echo "  - La app no está guardando el token"
echo "  - Verifica MyFirebaseMessagingService.kt"
echo "  - Verifica que onNewToken() se ejecute"
echo ""

echo "2️⃣ Verificando estado de la función..."
firebase --project=$PROJECT functions:list 2>/dev/null | grep sendUpdateEvent || echo "❌ Función no encontrada"
echo ""

echo "3️⃣ Últimos errores:"
firebase --project=$PROJECT functions:log --only sendUpdateEvent --filter error --lines 5 2>/dev/null
echo ""

echo "4️⃣ Posibles causas del error 404 '/batch':"
echo ""
echo "   a) Tokens FCM inválidos o mal formateados"
echo "   b) Problema con firebase-admin SDK"
echo "   c) Proyecto Firebase mal configurado"
echo "   d) API de FCM no habilitada"
echo ""

echo "5️⃣ Soluciones recomendadas:"
echo ""
echo "   Opción 1: Verificar tokens en Firestore"
echo "   --------"
echo "   1. Abre Firebase Console"
echo "   2. Ve a Firestore Database"
echo "   3. Collection 'users'"
echo "   4. Verifica que tengan campo 'fcmToken' con valor"
echo ""
echo "   Opción 2: Habilitar API de FCM"
echo "   --------"
echo "   1. https://console.cloud.google.com/apis/library/fcm.googleapis.com"
echo "   2. Selecciona proyecto: $PROJECT"
echo "   3. Clic en 'ENABLE'"
echo ""
echo "   Opción 3: Regenerar tokens en la app"
echo "   --------"
echo "   1. Desinstala la app del dispositivo"
echo "   2. Reinstala: ./gradlew installDebug"
echo "   3. Abre la app y login"
echo "   4. Verifica logs: adb logcat | grep FCM"
echo ""
echo "   Opción 4: Actualizar Cloud Function"
echo "   --------"
echo "   cd /home/alain/proyectos/kotlin/AgendaColaborativa"
echo "   firebase --project=$PROJECT deploy --only functions:sendUpdateEvent"
echo ""

echo "6️⃣ Ver logs en tiempo real:"
echo "   ./functions/monitor-logs.sh"
echo ""
